spring:
  datasource:
    url: jdbc:mysql://localhost:3306/college?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/yunxiaosheng/**/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    default-fetch-size: 100